import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased bg-gray-50">
        {/* Navigation Bar */}
        <header className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-lg font-bold">Calculators</h1>
            <nav>
              <ul className="flex space-x-6">
                <li>
                  <Link
                    prefetch={false}
                    href="/gold-calculator"
                    className="text-white hover:text-yellow-300"
                  >
                    Gold Calculator
                  </Link>
                </li>
                <li>
                  <Link
                    prefetch={false}
                    href="/usd-to-toman"
                    className="text-white hover:text-yellow-300"
                  >
                    USD Calculator
                  </Link>
                </li>

                <li>
                  <Link
                    prefetch={false}
                    href="/xau-to-gold"
                    className="text-white hover:text-yellow-300"
                  >
                    XAU Calculator
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="container mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}
